run:
  timeout: 10m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - gocritic
    - godot
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - whitespace

linters-settings:
  goconst:
    ignore-tests: true
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-specific: true
  revive:
    # make sure error-strings issues actually surface (default confidence is 0.8)
    confidence: 0.6
    rules:
      - name: context-keys-type
      - name: duplicated-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: errorf
      - name: superfluous-else
      - name: unreachable-code
      - name: bool-literal-in-expr
      - name: constant-logical-expr

issues:
  exclude-dirs:
    - pkg/client

  max-same-issues: 0
  max-issues-per-linter: 0
